/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 tierra.glb 
Author: uperesito (https://sketchfab.com/uperesito)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tierra-v11-0b460c8d3b524c049db5414f98e5819d
Title: Tierra v1.1
*/

import { useGLTF } from '@react-three/drei'

export function World(props) {
  const { nodes, materials } = useGLTF('/models/tierra.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.1}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.Tierra} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Nubes} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/tierra.glb')
